// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCraCOkWkfkT09QyPLQcFCoAlBRCJTx-2c',
    appId: '1:172098936453:web:9c8a1f6fdbf3d877c913ec',
    messagingSenderId: '172098936453',
    projectId: 'memory-lane-e3455',
    authDomain: 'memory-lane-e3455.firebaseapp.com',
    storageBucket: 'memory-lane-e3455.appspot.com',
    measurementId: 'G-WSGSC4GX01',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvWHGRHjN05j0iW1ErgUaTWurMWZh9juI',
    appId: '1:172098936453:android:42c66015346e4139c913ec',
    messagingSenderId: '172098936453',
    projectId: 'memory-lane-e3455',
    storageBucket: 'memory-lane-e3455.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiuljPDEq3qaAz6zjScpm40Jv2J2olUks',
    appId: '1:172098936453:ios:5d355c79d46218b3c913ec',
    messagingSenderId: '172098936453',
    projectId: 'memory-lane-e3455',
    storageBucket: 'memory-lane-e3455.appspot.com',
    iosBundleId: 'com.example.memoryLane',
  );
}
